<?php
	$query = $param['query'];
	$facetly_search_limit = Mage::getStoreConfig('facetly_limit');
	$action = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB)."find";
	$facetly_form = '			
			<div class="block">
				<div class="block-title">
					<strong><span>Search</span></strong>
				</div>
				<div class="block-content">
					<form action="'.$action.'" facetly_form="on" method="get">
						<input id="edit-query" type="text" facetly="on" name ="query" size ="15" value="'.$query.'" />	
						<input type="submit" value="Search" class="button" />
						<input id="edit-limit" type="hidden" value="'.$facetly_search_limit.'" name="limit">
					</form>
				</div>	
			</div>
			';
	echo $facetly_form;

?>